name: ciloka_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.11.0
  provider: ^6.1.5+1
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  google_sign_in: ^6.3.0
  firebase_core: ^4.2.0
  cached_network_image: ^3.4.1
  image_picker: ^1.2.0
  http: ^1.5.0
  mime: ^2.0.0
  path: ^1.9.1
  http_parser: ^4.1.2
  crypto: ^3.0.7
  uuid: ^4.5.2
  speech_to_text: ^7.3.0
  google_mlkit_text_recognition: ^0.13.0
  shared_preferences: ^2.5.3
  flutter_tts: ^4.2.3
  audioplayers: ^6.5.1
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/img/
    - assets/img/games/
    - assets/img/level/
    - assets/audio/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
