name: ciloka_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  audioplayers: ^6.5.1
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.3
  crypto: ^3.0.7
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_tts: ^4.2.3
  font_awesome_flutter: ^10.11.0
  google_mlkit_text_recognition: ^0.13.0
  google_sign_in: ^6.3.0
  http: ^1.5.0
  http_parser: ^4.1.2
  image_picker: ^1.2.0
  mime: ^2.0.0
  path: ^1.9.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  speech_to_text: ^7.3.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/ciloka-launcher.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/img/
    - assets/img/games/
    - assets/img/level/
    - assets/audio/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
